<?php

/**
 * ExtendedJobInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtendedJobInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtendedJobInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtendedJobInformation');
    }
}