<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('extended_job_information', 'extended_job_information_job_id_jobeet_job_id', array(
             'name' => 'extended_job_information_job_id_jobeet_job_id',
             'local' => 'job_id',
             'foreign' => 'id',
             'foreignTable' => 'jobeet_job',
             ));
        $this->addIndex('extended_job_information', 'extended_job_information_job_id', array(
             'fields' => 
             array(
              0 => 'job_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('extended_job_information', 'extended_job_information_job_id_jobeet_job_id');
        $this->removeIndex('extended_job_information', 'extended_job_information_job_id', array(
             'fields' => 
             array(
              0 => 'job_id',
             ),
             ));
    }
}